name: Deploy Node.js App to Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t muchamadagush/backend-sipul .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push muchamadagush/backend-sipul

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Docker Swarm on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.AWS_EC2_IP }}
        username: ubuntu
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          docker pull muchamadagush/backend-sipul
          docker stack deploy -c docker-stack.yml my-node-app
